version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "agile_monkeys", "-U", "root"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: flyway/flyway:11.1.0-alpine
    command: >
      -url=${SPRING_DATASOURCE_URL}
      -schemas=public
      -user=${SPRING_DATASOURCE_USERNAME}
      -password=${SPRING_DATASOURCE_PASSWORD}
      -locations=filesystem:/flyway/migrations
      migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/migrations
    depends_on:
      postgres:
        condition: service_healthy

  syntheticapi:
    image: crm-application:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: true
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: profile,email
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "{baseUrl}/login/oauth2/code/google"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_NAME: Google
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATION_URI: https://accounts.google.com/o/oauth2/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_TOKEN_URI: https://oauth2.googleapis.com/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_INFO_URI: https://www.googleapis.com/oauth2/v3/userinfo
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_NAME_ATTRIBUTE: sub
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: TRACE
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui/index.html
      APP_ADMIN_EMAILS: ${APP_ADMIN_EMAILS}
    depends_on:
      flyway:
        condition: service_completed_successfully
    volumes:
      - ./upload:/app/upload

volumes:
  postgres_data:
